import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,act,view,canPrepare} from '../engine.mjs';
import {GUESTS,STAFF,EMPERORS,STAFF_EFFECTS} from '../public/data.mjs';
import {actor,decide,finishGame} from './bot.mjs';
const seats=n=>Array.from({length:n},(_,i)=>({id:`p${i}`,name:`经理${i}`}));
const ready=(n=2,seed=9876)=>{let g=createGame(seats(n),seed);while(g.phase==='setup')g=act(g,actor(g),decide(g));return g;};
const cur=g=>g.players.find(p=>p.id===actor(g));
function drain(g){for(let i=0;i<200&&g.pending.length;i++)g=act(g,actor(g),decide(g));return g;}

test('physical base deck: 56 unique guests / 48 staff, exact orders and colors',()=>{assert.equal(Object.keys(GUESTS).length,56);assert.equal(Object.keys(STAFF).length,48);for(const c of Object.values(GUESTS)){assert.equal(c.order.length,4);assert.ok(c.order.reduce((s,n)=>s+n,0)>=1);assert.ok(c.order.every(n=>Number.isInteger(n)&&n>=0));}for(const c of ['blue','yellow','red','green'])assert.equal(Object.values(GUESTS).filter(g=>g.color===c).length,14);assert.equal(STAFF[17].cost,5);assert.deepEqual(GUESTS[94].order,[2,0,0,0]);assert.deepEqual(GUESTS[84].order,[0,2,1,0]);});
test('2/3/4-player dice count and snake order',()=>{for(const n of [2,3,4]){const g=ready(n);assert.equal(g.dice.reduce((s,n)=>s+n,0),6+n*2);assert.deepEqual(g.slots.slice(0,n).map(s=>s.player),g.slots.slice(n).map(s=>s.player).reverse());assert.ok(g.players.every(p=>p.hand.length===6&&p.cafe.length===1&&p.rooms.filter(Boolean).length===3));}});
test('hands, private offers, shuffled decks and PRNG are never sent to opponents',()=>{const g=ready(),p=g.players[0];g.pending=[{owner:p.id,label:'offer',effects:[{type:'offer',cards:[1,2,3]}]}];const v=view(g,g.players[1].id);assert.equal(v.players[0].hand,undefined);assert.equal(v.players[1].hand.length,6);assert.equal(v.pending[0].effects[0].cards,undefined);for(const k of ['rng','guestDeck','staffDeck'])assert.equal(v[k],undefined);});
test('wrong turn and invalid multi-step changes are atomic',()=>{const g=ready(),owner=actor(g),other=g.players.find(p=>p.id!==owner).id,before=structuredClone(g);assert.throws(()=>act(g,other,{type:'die',face:4}),/还没轮到/);assert.deepEqual(g,before);const p=cur(g);p.money=10;assert.throws(()=>act(g,owner,{type:'serve',allocations:[{guest:p.cafe[0].id,food:0,count:99}]}));assert.equal(p.money,10);});
test('setup requires three connected rooms from bottom-left, charging upper floors',()=>{let g=createGame(seats(2),5),who=actor(g);assert.throws(()=>act(g,who,{type:'setup',guest:4,rooms:[1,2,3]}),/左下角/);g=act(g,who,{type:'setup',guest:4,rooms:[0,5,10]});assert.equal(g.players.find(p=>p.id===who).money,7);assert.equal(canPrepare(g.players.find(p=>p.id===who),19),false);});
test('guest recruitment happens once and before the main die action',()=>{let g=ready(),id=actor(g);g=act(g,id,{type:'guest',guest:4});assert.throws(()=>act(g,id,{type:'guest',guest:4}),/每回合/);g.dice=[0,0,0,3,0,0];g=drain(act(g,id,{type:'die',face:4}));assert.throws(()=>act(g,id,{type:'guest',guest:4}),/每回合/);assert.throws(()=>act(g,id,{type:'die',face:4}),/已执行过/);});
test('cake/coffee ratios, free receiving and paid kitchen service are enforced',()=>{let g=ready();let id=actor(g);g.dice=[2,0,0,0,0,0];g=act(g,id,{type:'die',face:1});assert.throws(()=>act(g,id,{type:'resolve',index:0,secondary:2}),/不能多于/);g=act(g,id,{type:'resolve',index:0,secondary:1,allocations:[]});assert.deepEqual(cur(g).kitchen,[2,2,1,1]);assert.equal(cur(g).money,10);});
test('passing postpones turns; everyone passing removes one die and rerolls',()=>{let g=ready(),first=actor(g);const count=g.dice.reduce((a,b)=>a+b,0);for(let i=0;i<2;i++)g=act(g,actor(g),{type:'pass'});assert.equal(g.dustbin,1);assert.equal(g.dice.reduce((a,b)=>a+b,0),count-1);assert.equal(actor(g),first);assert.ok(g.slots.every(s=>!s.done));g=act(g,first,{type:'guest',guest:4});assert.throws(()=>act(g,first,{type:'pass'}),/已经开始/);});
test('six copies action strength without triggering employees tied to another die',()=>{let g=ready();const id=actor(g),p=cur(g);p.staff=[12,15,16,17,18,19,20];p.hand=[];g.dice=[0,0,0,0,0,2];g=act(g,id,{type:'die',face:6,target:4,boost:true});assert.equal(cur(g).money,9);assert.deepEqual(g.pending[0].effects,[{type:'funds',n:4,both:false,mandatory:true}]);g=act(g,id,{type:'resolve',index:0,favor:4});assert.equal(cur(g).emperor,4);assert.equal(cur(g).vp,0);});
test('Gizia does not remove a die, cannot boost or trigger staff',()=>{let g=ready(),id=actor(g);cur(g).staff=[13,17];g.dice=[3,0,0,0,0,0];g.pending=[{owner:id,label:'Gizia',effects:[{type:'bonusDie',n:1}]}];g=act(g,id,{type:'resolve',index:0,face:1,boost:true});assert.equal(g.dice[0],3);assert.equal(g.pending[0].effects[0].n,3);});
test('money cap, imperial overflow, once-per-round staff and room-group bonuses',()=>{let g=ready(),id=actor(g);cur(g).money=19;cur(g).emperor=12;g.pending=[{owner:id,label:'caps',effects:[{type:'money',n:5},{type:'favor',n:4}]}];g=drain(g);assert.equal(cur(g).money,20);assert.equal(cur(g).emperor,13);assert.equal(cur(g).vp,3);cur(g).staff=[1];g=drain(act(g,id,{type:'staff',staff:1}));assert.throws(()=>act(g,id,{type:'staff',staff:1}),/本轮已使用/);cur(g).cafe=[{id:63,served:[0,0,0,1]}];g=act(g,id,{type:'checkin',guest:63,room:0});g=drain(g);assert.equal(cur(g).vp,5);assert.ok(cur(g).bonuses.includes(0));});
test('emperor first scores old track, then retreats; 0 must suffer physical penalty',()=>{let g=ready(),id=actor(g);g.round=3;g.emperors[0]=EMPERORS.find(e=>e.id==='A1');g.slots.forEach(s=>s.done=true);g.slots.find(s=>s.number===g.turn.slot).done=false;g.turn.main=true;const p=cur(g);p.emperor=8;p.money=10;const q=g.players.find(q=>q.id!==id);q.emperor=0;q.money=3;g=act(g,id,{type:'end'});assert.equal(g.phase,'emperor');assert.equal(g.players.find(p=>p.id===id).vp,5);assert.equal(g.players.find(p=>p.id===id).emperor,5);g=drain(g);assert.equal(g.players.find(p=>p.id===id).money,13);assert.equal(g.players.find(p=>p.id===q.id).money,0);assert.equal(g.players.find(p=>p.id===q.id).vp,0);assert.equal(g.round,4);});
test('all 12 imperial tiles resolve their rewards and mandatory penalties',()=>{for(const tile of EMPERORS)for(const reward of [true,false]){let g=ready(),id=actor(g),p=cur(g);p.money=10;p.staff=[27,29,31];p.rooms=[2,1,1,1,1,1,1,1,1,1,2,1,1,1,1,2,1,1,1,1];p.hand=[1,2,3,4,5,6];g.pending=[{owner:id,label:tile.id,effects:reward?structuredClone(tile.bonus):[{type:'penalty',n:1,tile:tile.id,mandatory:true}]}];g=drain(g);assert.equal(g.pending.length,0,tile.id);}});
test('imperial hand penalties return cards to deck bottom in chosen order',()=>{let g=ready(),id=actor(g);cur(g).hand=[1,2,3];g.pending=[{owner:id,label:'A3',effects:[{type:'penalty',n:1,tile:'A3',mandatory:true}]}];g=act(g,id,{type:'resolve',index:0});assert.throws(()=>act(g,id,{type:'resolve',index:0,skip:true}),/必须执行/);g=act(g,id,{type:'resolve',index:0,cards:[3,1]});assert.deepEqual(g.staffDeck.slice(-2),[3,1]);assert.deepEqual(cur(g).hand,[2]);});
test('room groups cannot be farmed by removal and reoccupation',()=>{let g=ready(),id=actor(g);cur(g).rooms[0]=1;g.pending=[{owner:id,label:'occupy',effects:[{type:'occupy',n:1}]}];g=drain(g);assert.equal(cur(g).vp,2);cur(g).rooms[0]=1;g.pending=[{owner:id,label:'occupy again',effects:[{type:'occupy',n:1}]}];g=drain(g);assert.equal(cur(g).vp,2);});
test('final scoring includes post-retreat Operator and optimal opposing Secretary copy',()=>{let g=ready(),id=actor(g),p=cur(g),other=g.players.find(q=>q.id!==id);p.vp=10;p.emperor=10;p.money=4;p.kitchen=[1,2,0,0];p.rooms=Array(20).fill(0);for(const i of [0,5,10,15])p.rooms[i]=2;p.staff=[27,29,41];p.cafe=[{id:49,served:[0,0,0,0]}];other.staff=[30];other.emperor=7;g.round=7;g.emperors[2]=EMPERORS.find(e=>e.id==='C1');g.slots.forEach(s=>s.done=true);g.slots.find(s=>s.number===g.turn.slot).done=false;g.turn.main=true;g=drain(act(g,id,{type:'end'}));assert.equal(g.phase,'finished');assert.deepEqual(g.players.find(q=>q.id===id).score,{before:24,staff:9,rooms:10,left:7,guests:-5,total:45});});
test('each of 48 staff cards can be hired and each immediate effect can resolve',()=>{for(const card of Object.values(STAFF)){let g=ready(),id=actor(g);cur(g).hand=[card.id];cur(g).money=20;g.pending=[{owner:id,label:'hire',effects:[{type:'hire',n:1,discount:0}]}];g=act(g,id,{type:'resolve',index:0,staff:card.id});assert.ok(cur(g).staff.includes(card.id));g=drain(g);assert.equal(g.pending.length,0,card.name);}});
test('all 56 guests award their recorded points and execute their actual reward paths',()=>{for(const card of Object.values(GUESTS)){let g=ready(),id=actor(g),p=cur(g);p.money=20;p.cafe=[{id:card.id,served:[...card.order]}];p.rooms=Array(20).fill(1);const r=card.color==='green'?0:({blue:0,yellow:1,red:2}[card.color]);g=act(g,id,{type:'checkin',guest:card.id,room:r});assert.equal(cur(g).vp,card.vp);assert.equal(cur(g).rooms[r],2);g=drain(g);assert.equal(g.pending.length,0,card.name);}});
test('full seven-round matches for 2, 3 and 4 players end deterministically',()=>{for(const n of [2,3,4])for(let seed=1;seed<=12;seed++){const initial=createGame(seats(n),seed*10213),{game:g}=finishGame(initial);assert.equal(g.round,7);assert.ok(g.winners.length>=1);assert.ok(g.players.every(p=>p.money>=0&&p.money<=20&&p.emperor>=0&&p.emperor<=13&&Number.isInteger(p.vp)));assert.deepEqual(finishGame(initial).game,g);}});
