import {spawn} from 'node:child_process';
import {once} from 'node:events';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,mkdtemp,rm,readFile,writeFile,copyFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createApp} from '../server.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../.local/tests/security');
await mkdir(root,{recursive:true});
async function fixture(t,seed){const dir=await mkdtemp(path.join(root,'server-'));if(seed)await writeFile(path.join(dir,'rooms.json'),JSON.stringify(seed));const app=await createApp({dataDir:dir,rateLimit:10000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(async()=>{await app.close();await rm(dir,{recursive:true,force:true});});const base=`http://127.0.0.1:${app.server.address().port}`;const request=async(url,body,token)=>{const r=await fetch(base+url,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};let seq=0;const action=async(s,a)=>{const v=await request(`/api/rooms/${s.code}`,null,s.token);return request(`/api/rooms/${s.code}/action`,{revision:v.data.revision,requestId:`review-${++seq}`,action:a},s.token);};return {app,dir,base,request,action};}
test('standalone checkout boots and persists only below its own .local directory',async t=>{const dir=await mkdtemp(path.join(root,'standalone-'));await mkdir(path.join(dir,'public'));for(const file of ['server.mjs','paths.mjs','engine.mjs','undo.mjs','public/data.mjs'])await copyFile(new URL('../'+file,import.meta.url),path.join(dir,file));const script=`import {createApp} from ${JSON.stringify(pathToFileURL(path.join(dir,'server.mjs')).href)};const app=await createApp();app.server.listen(0,'127.0.0.1',()=>process.send({port:app.server.address().port}));process.on('message',async()=>{await app.close();process.exit(0);});`;const child=spawn(process.execPath,['--input-type=module','-e',script],{env:{...process.env,GAH_DATA_DIR:'',PORT:'0'},stdio:['ignore','ignore','pipe','ipc']});t.after(async()=>{if(child.exitCode===null){const exit=once(child,'exit');child.kill('SIGKILL');await exit;}await rm(dir,{recursive:true,force:true});});const [{port}]=await once(child,'message');assert.equal((await fetch(`http://127.0.0.1:${port}/api/rooms`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Standalone'})})).status,200);const saved=JSON.parse(await readFile(path.join(dir,'.local/AgentData/GrandAustriaHotel-0/rooms.json'),'utf8'));assert.equal(Object.keys(saved).length,1);const exit=once(child,'exit');child.send('close');assert.equal((await exit)[0],0);});
test('data lock survives competing processes and recovers after forced child termination',async t=>{const dir=await mkdtemp(path.join(root,'crash-'));const script=`import {createApp} from ${JSON.stringify(new URL('../server.mjs',import.meta.url).href)};const app=await createApp({dataDir:process.env.REVIEW_DIR});app.server.listen(0,'127.0.0.1',()=>process.send({port:app.server.address().port}));`;const child=spawn(process.execPath,['--input-type=module','-e',script],{env:{...process.env,REVIEW_DIR:dir},stdio:['ignore','ignore','pipe','ipc']});t.after(async()=>{if(child.exitCode===null&&!child.killed){const exit=once(child,'exit');child.kill('SIGKILL');await exit;}await rm(dir,{recursive:true,force:true});});const [{port}]=await once(child,'message');const saved=await fetch(`http://127.0.0.1:${port}/api/rooms`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Durable'})}).then(r=>r.json());await assert.rejects(createApp({dataDir:dir}),/数据目录.*占用/);const before=await readFile(path.join(dir,'rooms.json'),'utf8');const exit=once(child,'exit');child.kill('SIGKILL');await exit;const recovered=await createApp({dataDir:dir});await recovered.close();assert.equal(await readFile(path.join(dir,'rooms.json'),'utf8'),before);assert.ok(JSON.parse(before)[saved.code]);});
test('bad save startup releases lock without overwriting data',async()=>{const dir=await mkdtemp(path.join(root,'bad-save-'));try{await writeFile(path.join(dir,'rooms.json'),'broken');for(let i=0;i<2;i++)await assert.rejects(createApp({dataDir:dir}),/无法读取存档/);assert.equal(await readFile(path.join(dir,'rooms.json'),'utf8'),'broken');}finally{await rm(dir,{recursive:true,force:true});}});
test('PowerShell launcher is idempotent on an existing random loopback port',{skip:process.platform!=='win32'},async t=>{const f=await fixture(t);const script=fileURLToPath(new URL('../start.ps1',import.meta.url));const child=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',script,'-Port',String(f.app.server.address().port),'-DataDir',f.dir],{env:{...process.env,GAH_DATA_DIR:f.dir},stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',c=>output+=c);child.stderr.on('data',c=>output+=c);const [code]=await once(child,'exit');assert.equal(code,0,output);assert.match(output,/Already running/);assert.equal((await f.request('/api/health')).status,200);});
test('runtime paths retain KB primary path, isolate ports, and keep standalone data local',async t=>{
 const {runtimePaths}=await import('../paths.mjs');
 const fixture=await mkdtemp(path.join(root,'paths-'));t.after(()=>rm(fixture,{recursive:true,force:true}));
 const project=path.join(fixture,'repos','hotel');await mkdir(project,{recursive:true});await mkdir(path.join(fixture,'wiki'));await writeFile(path.join(fixture,'AGENTS.md'),'fixture');await writeFile(path.join(fixture,'wiki','index.md'),'fixture');
 const primary=runtimePaths({projectDir:project,port:3210,env:{}});assert.equal(primary.dataDir,path.join(fixture,'.local/AgentData/GrandAustriaHotel'));
 assert.notEqual(runtimePaths({projectDir:project,port:3211,env:{}}).dataDir,primary.dataDir);
 const standalone=runtimePaths({projectDir:path.join(fixture,'standalone'),port:3210,env:{}});assert.equal(standalone.dataDir,path.join(fixture,'standalone','.local/AgentData/GrandAustriaHotel'));
 assert.equal(runtimePaths({projectDir:project,env:{GAH_DATA_DIR:root}}).dataDir,root);
});
test('LOGIC-03 finished rooms are retained but release active capacity',async t=>{const seed=Object.fromEntries(Array.from({length:100},(_,i)=>{const code=i.toString(16).padStart(6,'0').toUpperCase();return [code,{code,host:'host',seats:[{id:'host',token:'a'.repeat(64),name:'Host',ready:true}],game:i===0?{phase:'finished',evidence:'retained result'}:null,revision:0,receipts:{}}];}));const f=await fixture(t,seed);assert.equal((await f.request('/api/rooms',{name:'New'})).status,200);const disk=JSON.parse(await readFile(path.join(f.dir,'rooms.json'),'utf8'));for(const [code,room] of Object.entries(seed))assert.deepEqual(disk[code],room);assert.equal(Object.keys(disk).length,101);assert.equal((await f.request('/api/rooms',{name:'Over capacity'})).status,400);});
test('LOGIC-01 same data directory rejects another writer and releases on close',async t=>{const f=await fixture(t);let second;try{await assert.rejects(async()=>{second=await createApp({dataDir:f.dir});},/数据目录.*占用/);}finally{await second?.close();}await f.app.close();const restored=await createApp({dataDir:f.dir});await restored.close();});
test('SEC-01 leaving revokes every old SSE before later broadcasts',async t=>{const f=await fixture(t),host=(await f.request('/api/rooms',{name:'Host'})).data,guest=(await f.request(`/api/rooms/${host.code}/join`,{name:'Guest'})).data;const ctrl=new AbortController();t.after(()=>ctrl.abort());const streams=await Promise.all([1,2].map(async()=>{const r=await fetch(`${f.base}/api/rooms/${host.code}/events`,{headers:{Authorization:`Bearer ${guest.token}`},signal:ctrl.signal});const reader=r.body.getReader();await reader.read();return reader;}));assert.equal((await f.action(guest,{type:'leave'})).data.left,true);assert.equal((await f.request(`/api/rooms/${host.code}`,null,guest.token)).status,401);await f.request(`/api/rooms/${host.code}/join`,{name:'Replacement'});for(const reader of streams){const result=await Promise.race([(async()=>{for(;;){const r=await reader.read();if(r.done)return 'closed';if(new TextDecoder().decode(r.value).includes('Replacement'))return 'leaked';}})(),new Promise(r=>setTimeout(()=>r('open'),500))]);assert.equal(result,'closed');}});
