import {chromium} from 'playwright';
import {mkdir,mkdtemp,rm} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {createApp} from '../server.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../.local/tests/security');await mkdir(root,{recursive:true});const dir=await mkdtemp(path.join(root,'browser-'));
const app=await createApp({dataDir:dir});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`;
const browser=await chromium.launch({headless:true,...(process.env.GAH_BROWSER?{executablePath:process.env.GAH_BROWSER}:{channel:'chrome'}),downloadsPath:dir});
try{const host=await fetch(base+'/api/rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Host'})}).then(r=>r.json());const context=await browser.newContext(),page=await context.newPage();page.setDefaultTimeout(6000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);const join=async()=>{await page.locator('#nickname').fill('Guest');await page.locator('#room-code').fill(host.code);await page.locator('[data-action=join]').click();await page.locator('.room-code').waitFor();};await join();const old=await page.evaluate(code=>JSON.parse(localStorage.getItem('gah.sessions'))[code],host.code);await page.locator('[data-action=leave]').click();await page.locator('#nickname').waitFor();assert.equal(await page.evaluate(code=>Boolean(JSON.parse(localStorage.getItem('gah.sessions'))[code]),host.code),false,'leave must remove saved seat');await join();const current=await page.evaluate(code=>JSON.parse(localStorage.getItem('gah.sessions'))[code],host.code);assert.notEqual(current.token,old.token);console.log('PASS leave clears credential and UI rejoins same room');
await page.evaluate(({old})=>localStorage.setItem('gah.sessions',JSON.stringify({[old.code]:old})),{old});await page.reload();await page.locator('#nickname').waitFor();assert.equal(await page.evaluate(code=>Boolean(JSON.parse(localStorage.getItem('gah.sessions'))[code]),host.code),false,'explicit 401 clears revoked credential');assert.match(await page.locator('#toast').innerText(),/失效|重新加入/);console.log('PASS explicit 401 permits new join');
await page.evaluate(s=>localStorage.setItem('gah.sessions',JSON.stringify({[s.code]:s})),current);await page.route('**/api/rooms/**',route=>route.abort('failed'));await page.goto(base+'/#'+host.code);await page.reload();await page.locator('#nickname').waitFor();assert.deepEqual(await page.evaluate(code=>JSON.parse(localStorage.getItem('gah.sessions'))[code],host.code),current,'network failures must preserve credentials');await page.unroute('**/api/rooms/**');await page.locator('[data-action=resume]').click();await page.locator('.room-code').waitFor();assert.deepEqual(errors,[]);console.log('PASS network error preserves credential and reconnects; no browser JS errors');
}finally{await browser.close();await app.close();await rm(dir,{recursive:true,force:true});}
